# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a52d7646520b3c93e98d25a38188086bd71fad084e82e63475e708e710c6d0b7684d6549f88ce955ab58b2ff339a5fb1ca580374788f3236d2215a4aace167a6

test:
  secret_key_base: e0b2d516b618d2a76082afc91224c0aca43c72894fc2bc364c1c22ae496ec962fd24608d7cfd89f3e818c975f499a6775c00b3f2076f7bdc0c7f376d6817fc39

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
